var templistGlobal={
	suggest:'<li>\
	<a href="/item/<%id%>" data-id="<%id%>" title="<%name%>" target="_blank"><%name%></a>\
	</li>',
	articleList:'<li class="item cl" data-id="<%id%>">'
					+'<div class="pic">'
						+'<a href="<%href%>" target="_blank"><img data-src="<%pic_url%>" alt="<%title%>"></a>'
					+'</div>'
					+'<div class="info">'
					+'<p class="title"><a href="<%href%>" target="_blank" title="<%title%>"><%title%></a></p>'
					+'<div class="goods">'
						+'<a href="/item/<%goods_id%>" target="_blank"><%goods_info.name%></a>'
					+'</div>'
					+'<p class="desc"><%summary%></p>'
					+'<div class="meta cl">'
						+'<div class="fl">'
							+'<span class="author"><%author%></span>'
							+'<span class="source"><%source%></span>'
						+'</div>'
						+'<ul class="count fr">'
							+'<li class="lk"><a href="<%href%>" target="_blank"><i class="icon"></i><%view_cnt%></a></li>'
							+'<li class="gd"><a href="<%href%>" target="_blank"><i class="icon"></i><%like_cnt%></a></li>'
							+'<li class="cmt"><a href="<%href%>#comment" target="_blank"><i class="icon"></i><%comment_cnt%></a></li>'
						+'</ul>'
					+'</div>'
				+'</div>'
			+'</li>',
			goodslist:'<li class="item" >'
				+'<div class="pic"><a href="/item/<%id%>" target="_blank"><img data-src="<%? echo(pic_url||def.defaultPic) ?%>" alt="<%name%>" /></a></div>'
				+'<div class="info">'
					+'<p class="title"><a href="/item/<%id%>" target="_blank"><%name%></a></p>'
					+'<div class="args"'
						+'<p>类别：<a href="/category/<%cate_id%>"><%cate_info.name%></a></p>'
						+'<p>'
							+'<span>体验文章：<a href="/item/<%id%>" target="_blank"><%?print(atc_cnt||0)?%>篇</a></span>'
							+'<span>收藏：<%?print(fav_cnt||0)?%></span>'
							+'<span>已拥有：<%?print(pss_cnt||0)?%>人</span>'
						+'</p>'
					+'</div>'
					+'<a href="/item/<%id%>" class="btn" target="_blank">查看该商品</a>'
				+'</div>'
			+'</li>'
}